### ISSUE TITLE
failed to open device access denied (insufficient permissions)

### ISSUE THREAD

**Issue by bossmoney** [nmeum/android-tools#169] opened 2024-11-30 19:07 UTC
when i input adb devices ,i get failed to open device access denied (insufficient permissions)

can add fileDescriptor in commonLine
maybe it is like: adb devices -fd 66
then i can open usb device that fileDescriptor is 66

This is details in libusb:
https://github.com/libusb/libusb/blob/master/android/README

```
Runtime Permissions:
--------------------

The Runtime Permissions on Android can be transferred from Java to Native
over the following approach:

  JAVA:

   --> Obtain USB permissions over the android.hardware.usb.UsbManager class

      usbManager = (UsbManager) getSystemService(Context.USB_SERVICE);
      HashMap<String, UsbDevice> deviceList = usbManager.getDeviceList();
      for (UsbDevice usbDevice : deviceList.values()) {
          usbManager.requestPermission(usbDevice, mPermissionIntent);
      }

   --> Get the native FileDescriptor of the UsbDevice and transfer it to
       Native over JNI or JNA

      UsbDeviceConnection usbDeviceConnection = usbManager.openDevice(camDevice);
      int fileDescriptor = usbDeviceConnection.getFileDescriptor();

   --> JNA sample method:

      JNA.INSTANCE.set_the_native_Descriptor(fileDescriptor);

  NATIVE:

   --> Initialize libusb on Android

      set_the_native_Descriptor(int fileDescriptor) {
          libusb_context *ctx;
          libusb_device_handle *devh;
          libusb_set_option(&ctx, LIBUSB_OPTION_NO_DEVICE_DISCOVERY, NULL);
          libusb_init(&ctx);
          libusb_wrap_sys_device(NULL, (intptr_t)fileDescriptor, &devh);
      }
      /* From this point you can regularly use all libusb functions as usual */

   About LIBUSB_OPTION_NO_DEVICE_DISCOVERY:

    The method libusb_set_option(&ctx, LIBUSB_OPTION_NO_DEVICE_DISCOVERY, NULL)
    does not affect the ctx.
    It allows initializing libusb on unrooted Android devices by skipping
    the device enumeration.
```

**Comment by bossmoney** [comment] 2024-11-30 19:12
i use adb in termux on android
so i get this problem，and how to build android-tools then i can use adb in termux on android

**Comment by Biswa96** [comment] 2024-11-30 19:36
I can not reproduce the issue. `adb devices -l` is working fine in termux (terminal emulator in Android) and in Linux desktop. There could be some extra quirks in your device which is out of scope of this project.

**Closed by Biswa96** 2024-11-30 19:36 UTC

**Comment by Biswa96** [comment] 2024-12-02 17:01
This seems to be expected behavior due to all the restrictions in Android. Native Android platform is not the intended use case for this project.

Please report the issue in termux-packages repository. I've seen some discussions about libusb and termux-api. WiFi debugging works with adb in termux without any extra setup.
